apiVersion: apps/v1
kind: Deployment
metadata:
  name: arm-portal-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: arm-portal
  template:
    metadata:
      labels:
        app: arm-portal
    spec:
      containers:
        - name: arm-portal-container
          image: khalifan1126/amr_portal:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: arm-portal-service
spec:
  selector:
    app: arm-portal
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP  
