apiVersion: apps/v1
kind: Deployment
metadata:
  name: amr-portal-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: amr-portal
  template:
    metadata:
      labels:
        app: amr-portal
    spec:
      containers:
        - name: amr-portal-container
          image: khalifan1126/amr_portal:latest
          ports:
            - containerPort: 80
          env:
            - name: NEXT_PUBLIC_API_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: amr-portal-env-secrets
                  key: NEXT_PUBLIC_API_BASE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: amr-portal-service
spec:
  selector:
    app: amr-portal
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
